// <auto-generated />
using System;
using ChamadaGirneManagement.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChamadaGirneManagement.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ChamadaGirneManagement.Domain.Entities.Uygulama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GecisYolu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("HedefKullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IstemciAnahtarHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<int>("SiraNo")
                        .HasColumnType("int");

                    b.Property<string>("UygulamaAdi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("UygulamaKodu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("UygulamaKodu")
                        .IsUnique();

                    b.ToTable("Uygulamalar", (string)null);
                });

            modelBuilder.Entity("ChamadaGirneManagement.Domain.Entities.UygulamaGecisKodu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KodHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("KullanildiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("SonKullanmaTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UygulamaId")
                        .HasColumnType("int");

                    b.Property<string>("YonetimDonusAdresi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("YonetimKullaniciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KodHash")
                        .IsUnique();

                    b.HasIndex("UygulamaId");

                    b.HasIndex("YonetimKullaniciId");

                    b.ToTable("UygulamaGecisKodlari", (string)null);
                });

            modelBuilder.Entity("ChamadaGirneManagement.Domain.Entities.YonetimKullanicisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.ToTable("YonetimKullanicilari", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdSoyad = "Sistem Yöneticisi",
                            KullaniciAdi = "IT",
                            SifreHash = "$2a$11$nB8kNi06IPQiG//LeYdNqe10O54oTT9NvQ5QASZ641yBgrbT9mZlq"
                        });
                });

            modelBuilder.Entity("ChamadaGirneManagement.Domain.Entities.UygulamaGecisKodu", b =>
                {
                    b.HasOne("ChamadaGirneManagement.Domain.Entities.Uygulama", "Uygulama")
                        .WithMany()
                        .HasForeignKey("UygulamaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChamadaGirneManagement.Domain.Entities.YonetimKullanicisi", "YonetimKullanicisi")
                        .WithMany()
                        .HasForeignKey("YonetimKullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uygulama");

                    b.Navigation("YonetimKullanicisi");
                });
#pragma warning restore 612, 618
        }
    }
}
